language: bash
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
script:
  - bats test
before_deploy:
  - mkdir dist
  - tar czf dist/scryptor.tar.gz bin/
deploy:
  provider: releases
  api_key:
    secure: "QYgPUMOHvtwVJMrtBX8zlwITs7pdVLFvD07N1kQUIfdhN6L76UElH0qJ6Whgq0sF6SBpK3oT1hQ/oj1CGVHHd5Is/I801jArspRfKFngwuy+Re/GObNBruAovqx6ZAIOdPdemFPliMsW9QKqsqmddUgSy4vqnR+OahVgKCdhTok="
  file: "dist/scryptor.tar.gz"
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    on_success: never